In [1]:
import torch

In [47]:
B, Q, K, H = 2, 2, 3, 5

queries = torch.arange(B * Q * H).reshape((B, Q, H))
keys = torch.arange(B * K * H).reshape((B, K, H)) / 2



# queries = queries.unsqueeze(2)

In [30]:
print(f"{queries=}")
# print(f"{keys=}")


print(f"{queries.shape=}")
# print(f"{keys.shape=}")

queries=tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
queries.shape=torch.Size([2, 2, 2])


In [32]:
import torch

a = torch.tensor([[1.],
                  [2.],
                  [3.]])   # shape (3,1)

b = torch.tensor([10,20,30])   # shape (3,)

# both will expand to 3, 3. the length of rows in A will repeat 3 times
# the rows of B will expand 3 times

# QUESTION: Without changing shapes manually (no expand, no repeat),
# what is (a + b).shape ?
# and what does the actual tensor look like?

In [34]:
X = torch.arange(12.).reshape(3,4) *  # shape (3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
bias = torch.tensor([1., 2., 3., 4.])  
bias

tensor([1., 2., 3., 4.])

In [36]:
X + bias

tensor([[ 1.,  3.,  5.,  7.],
        [ 5.,  7.,  9., 11.],
        [ 9., 11., 13., 15.]])

In [40]:
p = torch.tensor([1., 2., 3.])   # shape (3,)
q = torch.tensor([10., 20.])     # shape (2,)

# QUESTION: Use broadcasting to create a (3,2) matrix
# where entry (i,j) = p[i] + q[j].
# (hint: p[:, None] + q[None, :])

q[None, ...]
p[..., None]

tensor([[1.],
        [2.],
        [3.]])

In [66]:
queries = torch.randn((Q, H))
display(queries)
print()
keys = torch.randn((K, H))
display(keys)

queries = queries.unsqueeze(1)
queries_expanded = queries.repeat((1, K, 1))
print(f"{queries_expanded=}")

# both will become 3, 2, 5, query, key, hdim.
# for each query, we will add three keys
# 
keys = keys.unsqueeze(0) 
keys_expanded = keys.repeat((Q, 1, 1))
print(f"{keys_expanded=}")

print(keys_expanded + queries_expanded)

print(keys + queries)


tensor([[-0.3840, -1.5007, -0.6471,  0.5240,  0.4686],
        [ 0.1221,  0.1029,  0.4387, -1.0729,  0.8491]])

tensor([[ 1.6653,  0.0642, -0.6836,  1.9718,  0.0278],
        [-0.2448, -1.3074,  0.5601, -1.6706, -0.5161],
        [-0.0216,  0.0755,  2.5258,  0.7418, -0.2321]])

queries_expanded=tensor([[[-0.3840, -1.5007, -0.6471,  0.5240,  0.4686],
         [-0.3840, -1.5007, -0.6471,  0.5240,  0.4686],
         [-0.3840, -1.5007, -0.6471,  0.5240,  0.4686]],

        [[ 0.1221,  0.1029,  0.4387, -1.0729,  0.8491],
         [ 0.1221,  0.1029,  0.4387, -1.0729,  0.8491],
         [ 0.1221,  0.1029,  0.4387, -1.0729,  0.8491]]])
keys_expanded=tensor([[[ 1.6653,  0.0642, -0.6836,  1.9718,  0.0278],
         [-0.2448, -1.3074,  0.5601, -1.6706, -0.5161],
         [-0.0216,  0.0755,  2.5258,  0.7418, -0.2321]],

        [[ 1.6653,  0.0642, -0.6836,  1.9718,  0.0278],
         [-0.2448, -1.3074,  0.5601, -1.6706, -0.5161],
         [-0.0216,  0.0755,  2.5258,  0.7418, -0.2321]]])
tensor([[[ 1.2813, -1.4365, -1.3306,  2.4958,  0.4964],
         [-0.6288, -2.8081, -0.0870, -1.1466, -0.0475],
         [-0.4056, -1.4252,  1.8787,  1.2658,  0.2365]],

        [[ 1.7874,  0.1671, -0.2448,  0.8989,  0.8770],
         [-0.1227, -1.2045,  0.9988, -2.7435,  0.3330],
       